# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: ocean
day_night: false
font: native
font_size: L

# SEO

site_type: Organization
local_business_type: ''
org_name: ''
description: My research group description.
twitter: ''

# Contact (edit or remove options as required)

email: test@example.org 测试待更改
phone: 888 888 88 88 测试待更改
address:
  street: 邯郸路220号
  city: 杨浦区
  region: 上海
  postcode: '200000'
  country: China
  country_code: +86
# coordinates:
#   latitude: '31.20294'
#   longitude: '121.463295'
directions: 科学楼403
office_hours:
  - 'Monday 10:00 to 13:00' 
  - 'Wednesday 09:00 to 10:00'
# appointment_url: 'https://calendly.com'
contact_links:
 - icon: envelope
   icon_pack: fas
   name: Discuss on Forum
   link: 'mailto:493907205@qq.com'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
math: false
diagram: false
privacy_pack: false
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: false
    post: false
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
